openapi: 3.0.0
info:
  title: Ballerina Package File Proxy
  description: This API proxies requests to Ballerina package files, handling specific package versions and file requests.
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /org/ballerinalang/{package}/{version}/{file}:
    get:
      summary: Retrieve Ballerina package file
      description: |
        This endpoint retrieves a specific file from a Ballerina package version.
        It handles requests for different packages, versions, and files within the Ballerina organization.
      parameters:
        - name: package
          in: path
          required: true
          description: The name of the Ballerina package
          schema:
            type: string
            example: ballerina-parser
        - name: version
          in: path
          required: true
          description: The version of the Ballerina package
          schema:
            type: string
            example: 2201.8.2
        - name: file
          in: path
          required: true
          description: The specific file to retrieve from the package
          schema:
            type: string
            example: ballerina-parser-2201.8.2.module
      responses:
        '200':
          description: Successful response
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '302':
          description: Redirect response
          headers:
            Location:
              description: URL to redirect to
              schema:
                type: string
        '404':
          description: File not found
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Unknown error
